services:
  website:
    container_name: simple-tracking-site
    build: .
    ports:
      - "8000:8000"
      - "8888:8888"
    volumes:
      - ~/.aws:/root/.aws
      - ./src:/app/src
      - ./data:/app/data
    environment:
      PGPASSWORD: "1234"

  database:
    container_name: simple-tracking-db
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "tracking"
      PGPASSWORD: "1234"
    volumes:
      - tracking-db-data:/var/lib/postgresql/data
      - ./data/dumps/:/dumps/
    ports:
      - "5432:5432"
    command: >
      -c max_wal_size=10GB
    restart: unless-stopped

volumes:
  tracking-db-data:


