export default {
  p1_received: 'National legislation, policy and financing',
  p2_received: 'IHR coordination, communication and advocacy',
  p3_received: 'Antimicrobial resistance (AMR)',
  p4_received: 'Zoonotic disease',
  p5_received: 'Food safety',
  p6_received: 'Biosafety and biosecurity',
  p7_received: 'Immunization',
  d1_received: 'National laboratory system',
  d2_received: 'Real-time surveillance',
  d3_received: 'Reporting',
  d4_received: 'Workforce development',
  r1_received: 'Preparedness',
  r2_received: 'Emergency response operations',
  r3_received: 'Linking public health and security authorities',
  r4_received: 'Medical countermeasures and personnel deployment',
  r5_received: 'Risk communication',
  re_received: 'Radiation events',
  poe_received: 'Points of entry',
  ce_received: 'Chemical events',
  p1_disbursed: 'National legislation, policy and financing',
  p2_disbursed: 'IHR coordination, communication and advocacy',
  p3_disbursed: 'Antimicrobial resistance (AMR)',
  p4_disbursed: 'Zoonotic disease',
  p5_disbursed: 'Food safety',
  p6_disbursed: 'Biosafety and biosecurity',
  p7_disbursed: 'Immunization',
  d1_disbursed: 'National laboratory system',
  d2_disbursed: 'Real-time surveillance',
  d3_disbursed: 'Reporting',
  d4_disbursed: 'Workforce development',
  r1_disbursed: 'Preparedness',
  r2_disbursed: 'Emergency response operations',
  r3_disbursed: 'Linking public health and security authorities',
  r4_disbursed: 'Medical countermeasures and personnel deployment',
  r5_disbursed: 'Risk communication',
  re_disbursed: 'Radiation events',
  poe_disbursed: 'Points of entry',
  ce_disbursed: 'Chemical events',
} as { [key: string]: string }
