export default {
  p1_received: 'National legislation, policy and financing received',
  p2_received: 'IHR coordination, communication and advocacy received',
  p3_received: 'Antimicrobial resistance (AMR) received',
  p4_received: 'Zoonotic disease received',
  p5_received: 'Food safety received',
  p6_received: 'Biosafety and biosecurity received',
  p7_received: 'Immunization received',
  d1_received: 'National laboratory system received',
  d2_received: 'Real-time surveillance received',
  d3_received: 'Reporting received',
  d4_received: 'Workforce development received',
  r1_received: 'Preparedness received',
  r2_received: 'Emergency response operations received',
  r3_received: 'Linking public health and security authorities received',
  r4_received: 'Medical countermeasures and personnel deployment received',
  r5_received: 'Risk communication received',
  re_received: 'Radiation events received',
  poe_received: 'Points of entry received',
  ce_received: 'Chemical events received',
  p1_disbursed: 'National legislation, policy and financing disbursed',
  p2_disbursed: 'IHR coordination, communication and advocacy disbursed',
  p3_disbursed: 'Antimicrobial resistance (AMR) disbursed',
  p4_disbursed: 'Zoonotic disease disbursed',
  p5_disbursed: 'Food safety disbursed',
  p6_disbursed: 'Biosafety and biosecurity disbursed',
  p7_disbursed: 'Immunization disbursed',
  d1_disbursed: 'National laboratory system disbursed',
  d2_disbursed: 'Real-time surveillance disbursed',
  d3_disbursed: 'Reporting disbursed',
  d4_disbursed: 'Workforce development disbursed',
  r1_disbursed: 'Preparedness disbursed',
  r2_disbursed: 'Emergency response operations disbursed',
  r3_disbursed: 'Linking public health and security authorities disbursed',
  r4_disbursed: 'Medical countermeasures and personnel deployment disbursed',
  r5_disbursed: 'Risk communication disbursed',
  re_disbursed: 'Radiation events disbursed',
  poe_disbursed: 'Points of entry disbursed',
  ce_disbursed: 'Chemical events disbursed',
} as { [key: string]: string }
